Added german translations
AppFlowy-IO/AppFlowy pull request #289
Opened 2022-01-30 11:26 UTC by Aquitano

+ added de_DE.json
+ registered german locale

2022-01-30 14:57 UTC, lguenth requested changes
Hey, thanks for the translations! I was about to fork the repo when I saw your PR.
I just added some alternatives which might be more fitting. You also left lines 5 "githubStarText" and 22 "loginTitle" untranslated, so I made suggestions. :)
Hope this helps. :grinning:

2022-01-30 14:57 UTC, lguenth commented on frontend/app_flowy/assets/translations/de_DE.json
> +    "githubStarText": "Star on GitHub",
GitHub Star vergeben

2022-01-30 14:57 UTC, lguenth commented on frontend/app_flowy/assets/translations/de_DE.json
> +    "letsGoButtonText": "Lass Uns Anfangen",
Los geht's

2022-01-30 14:57 UTC, lguenth commented on frontend/app_flowy/assets/translations/de_DE.json
> +      "getStartedText": "Los geht's",
Erste Schritte

2022-01-30 14:57 UTC, lguenth commented on frontend/app_flowy/assets/translations/de_DE.json
> +      "loginTitle": "Login to @:appName",
Bei @:appName einloggen

2022-01-30 14:57 UTC, lguenth commented on frontend/app_flowy/assets/translations/de_DE.json
> +        "instruction4": "Drücken Sie auf die Knopf unten, wenn Sie die Anmeldung abgeschlossen haben:"
Klicken Sie unten auf die Schaltfläche, wenn Sie die Anmeldung abgeschlossen haben:

2022-02-02 07:55 UTC, Aquitano commented
Updated PR according to the suggestions.

2022-02-02 19:59 UTC, MikeWallaceDev requested changes
Could you please fix translation file name, it is in the wrong format. It should be "de-DE.json"  (dash, not underscore).

2022-02-05 03:34 UTC, MikeWallaceDev commented
@Aquitano , I'm looking at your PR now.  Did you disable the "allow edits and access to secrets by maintainers" button?  I am trying to push a small change and it's not working.

![image](https://user-images.githubusercontent.com/5375835/152627268-4d548ae6-f3fa-4586-a782-39309a76808c.png)

2022-02-05 09:30 UTC, Aquitano commented
@MikeWallaceDev. "Allow edits ... by maintainers" is checked/enabled
![Screenshot 2022-02-05 102729](https://user-images.githubusercontent.com/44656811/152636284-785a99da-40d8-433b-8690-260d0caf49dd.png)
.

2022-02-13 04:46 UTC, annieappflowy commented
This PR has been pending for a while. Should we convert it into a draft or should we merge the changes?

2022-02-25 18:49 UTC, merged