Changes language names to their respective languages
AppFlowy-IO/appflowy pull request #293
Opened 2022-02-01 20:41 UTC by bolshoytoster

Fixes #290

Some non-english speakers might find it hard to change their language
because they are all written in english.

This commit changes the language names in the selector to their
respective languages.

- Added two functions in `frontend/app_flowy/packages/flowy_infra/lib/language.dart`:
- - fullStringFromLanguage
- - languageFromFullString

These convert two and from the language's name and it's AppLanguage.

- '_LanguageSelectorDropdownState' now uses strings for the `value`
field, and converts using the afformentioned functions.

2022-02-02 00:56 UTC, appflowy commented
Hi, @bolshoytoster, Thank you for your improvements. But the CI seems not passed.
![image](https://user-images.githubusercontent.com/86001920/152076252-b17e0844-a8b0-4a87-933f-bdf236f488fd.png)

2022-02-02 08:00 UTC, bolshoytoster commented
@appflowy sorry, I wrote `String` with a lowercase.

2022-02-02 08:41 UTC, MikeWallaceDev commented
Hi there @bolshoytoster! Thanks for the PR, but you didn't need to add all that code. 
There's two ways to do this: either directly put the original language in en.json (and then not translate in the other languages), or just hard code the strings. Hard coding might be the better approach here. The languages will never be translated, they will always be shown in the original language. (i.e. "Français" will always be "Français" no matter what language the app is in)

2022-02-02 08:43 UTC, MikeWallaceDev requested changes
This must be changed to a simpler solution. There's no need for added functions.

2022-02-02 08:58 UTC, bolshoytoster commented
@appflowy
> or just hard code the strings

I can’t name the enums with non-ascii characters because dart doesn’t support it.

I’ll use en.json instead.

2022-02-02 16:41 UTC, bolshoytoster commented
@MikeWallaceDev

looking at [the way the translations are implemented](https://github.com/AppFlowy-IO/appflowy/blob/728d60239a34a73174e99c191299be0ab29b1f97/frontend/app_flowy/lib/workspace/domain/edit_action/view_edit.dart#L12-L34), wouldn't it be the same/worse than what I've already implemented.

> There's no need for added functions.

I would still have to add functions if I used the `en.json` method.

2022-02-03 01:14 UTC, appflowy commented
> @MikeWallaceDev
> 
> looking at [the way the translations are implemented](https://github.com/AppFlowy-IO/appflowy/blob/728d60239a34a73174e99c191299be0ab29b1f97/frontend/app_flowy/lib/workspace/domain/edit_action/view_edit.dart#L12-L34), wouldn't it be the same/worse than what I've already implemented.
> 
> > There's no need for added functions.
> 
> I would still have to add functions if I used the `en.json` method.

I think using enum is Ok, it is used to choose the language.

2022-02-03 02:58 UTC, MikeWallaceDev commented
Here is what I wrote to Nathan earlier, it should help you out : 

> However, easy_localization has an attribute called "supportedLocales" which contains all the Locales that we use in the app.  I suggest that we iterate through that, instead of having an enum.  That way, when a new language is added, if the dev forgets to update the enum, we won't be screwed.
> 
> For example, we just added German. It's not in the enum yet. The pseudo code would be: 
> iterate through "supportedLocales" {
>    if "en" then return "english"
>    if "fr" then return "Francais"
>    else return Locale.languageCode
> }
> 
> The user would see
> english
> Francais
> de
> 
> Obviously it's not perfect. But right now the German language just wouldn't appear.

2022-02-05 01:18 UTC, MikeWallaceDev commented
@bolshoytoster I refactored how the original language settings were handled. The enum no longer exists, all the functions have been removed.

You can see how I did it here : #306

2022-02-05 01:18 UTC, closed without merging