Fixed Issue no #3426
AppFlowy-IO/AppFlowy pull request #3440
Opened 2023-09-19 06:51 UTC by aryan-more

fixes #3426

Added Padding Between Edit Textfield and Select Type Dropdown

- [✅ ] My code adheres to the [AppFlowy Style Guide](https://appflowy.gitbook.io/docs/essential-documentation/contribute-to-appflowy/software-contributions/submitting-code/style-guides)
- [✅ ] I've listed at least one issue that this PR fixes in the description above.
- [❌ ] I've added a test(s) to validate changes in this PR, or this PR only contains semantic changes.
- [✅ ] All existing tests are passing.

2023-09-19 06:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/AppFlowy-IO/AppFlowy?pullRequest=3440) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/AppFlowy-IO/AppFlowy?pullRequest=3440) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/AppFlowy-IO/AppFlowy?pullRequest=3440) it.</sub>

2023-09-19 08:01 UTC, LucasXu0 commented on frontend/appflowy_flutter/pubspec.lock
> +      sha256: f092b211a4319e98e5ff58223576de6c2803db36221657b46c82574721240687
@aryan-more Please don't update the pubspec.lock

2023-09-20 04:15 UTC, richardshiue requested changes
A good start! A few suggestions:

- We have a VSpace class that you can use which is a bit more readable.
- The height of 8 and adding the 4 pre-exisiting whitespace to the top and bottom, makes this 16 in total, not 12
- If there aren't buttons to the bottom (see the primary field or the "Name" field in a new grid), the whitespace shouldn't be added.

2023-09-21 10:47 UTC, aryan-more commented
@richardshiue Thanks for suggesting the VSpace Widget. I added VSpace only to the Type Selection Dropdown since I noticed that the other two widgets already have padding, which is why I didn't add it to them.

2023-09-21 15:31 UTC, aryan-more commented
@richardshiue i was searching where does those two delete and hide button shows up i didn't able to find them ,thanks for sharing screenshot and it's now fixed

2023-09-22 01:36 UTC, richardshiue approved these changes
LGTM

2023-09-22 03:15 UTC, merged

2023-09-22 03:15 UTC, richardshiue commented
Merged, thanks for contributing!