added hindi translation
AppFlowy-IO/AppFlowy pull request #3575
Opened 2023-10-02 11:32 UTC by CrazyRikin

### Feature Preview
Hey , please check the hindi translation added in  /frontend/appflowy_flutter/assets/translations
fixes #2626 

#### PR Checklist

- [ ] My code adheres to the [AppFlowy Style Guide](https://appflowy.gitbook.io/docs/essential-documentation/contribute-to-appflowy/software-contributions/submitting-code/style-guides)
- [ ] I've listed at least one issue that this PR fixes in the description above.
- [ ] I've added a test(s) to validate changes in this PR, or this PR only contains semantic changes.
- [ ] All existing tests are passing.

2023-10-02 11:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/AppFlowy-IO/AppFlowy?pullRequest=3575) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/AppFlowy-IO/AppFlowy?pullRequest=3575) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/AppFlowy-IO/AppFlowy?pullRequest=3575) it.</sub>

2023-10-02 13:31 UTC, MayurSMahajan requested changes
Only submitting a translated JSON file is not enough, you have to make changes in the code to actually allow picking Hindi as a language.

Go through this documentation: 
https://docs.appflowy.io/docs/documentation/appflowy/translation

Review this merged PR to add a new language: 
https://github.com/AppFlowy-IO/AppFlowy/commit/a389836897c71efe69af64346e10d8748c06cf36

Also go through these: 
https://docs.appflowy.io/docs/documentation/software-contributions/conventions/git-conventions

2023-10-02 13:33 UTC, MayurSMahajan commented
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/47064215/666c6394-5999-4ed4-8bca-71661fc8ae7e)

Since you haven't added any tests in the PR please don't tick the box.
Same for following AppFlowy Style Guide.

2023-10-02 13:42 UTC, Xazin commented
> ![image](https://user-images.githubusercontent.com/47064215/271983498-666c6394-5999-4ed4-8bca-71661fc8ae7e.png)
> 
> Since you haven't added any tests in the PR please don't tick the box. Same for following AppFlowy Style Guide.

`or this PR only contains semantic changes.` - Translations are semantic changes, it's fine to check it off.

2023-10-02 15:09 UTC, CrazyRikin commented
> Only submitting a translated JSON file is not enough, you have to make changes in the code to actually allow picking Hindi as a language.
> 
> Go through this documentation: https://docs.appflowy.io/docs/documentation/appflowy/translation
> 
> Review this merged PR to add a new language: [a389836](https://github.com/AppFlowy-IO/AppFlowy/commit/a389836897c71efe69af64346e10d8748c06cf36)
> 
> Also go through these: https://docs.appflowy.io/docs/documentation/software-contributions/conventions/git-conventions

hey @MayurSMahajan then 
1) I should make changes in code to allow picking hindi ?
2) & make changes according to AppFlowy Style Guide?
these two tasks have to completed from my end right?

2023-10-02 15:17 UTC, MayurSMahajan commented
That's right. Review earlier PRs which added a new language for reference.

These checks run various tests on various platforms. So through these checks we ensure that your added changes don't break any existing feature in AppFlowy. There are a few other tests as well which check your Commit Lints, whether you have signed your CLA or not, etc.

2023-10-02 15:19 UTC, MayurSMahajan commented
Don't worry if a few checks fail. Right now our CI/CD is a bit broken.

2023-10-02 15:34 UTC, CrazyRikin commented
> Don't worry if a few checks fail. Right now our CI/CD is a bit broken.

sure thanks for your help.

2023-10-02 15:53 UTC, CrazyRikin commented
hey @MayurSMahajan ,i have made changes as we discussed .

2023-10-03 09:47 UTC, CrazyRikin commented
hey @MayurSMahajan will this pr will be merged?

2023-10-03 10:56 UTC, MayurSMahajan commented
@CrazyRikin  patience tiger 😁

2023-10-03 11:38 UTC, MayurSMahajan requested changes
Hey @CrazyRikin, it seems you have copy pasted your responses from Google Translate directly. Nothing wrong with that, we all do it. 

But you should modify them to feel more natural, consistent and modern.

By natural I mean they should sound like human,
By consistent I mean to use only one word instead of its variants as in the case of रिपीट and दोबारा 
By modern I mean, today's hindi audience is more familiar with words like साइन अप rather than दाखिल करना

2023-10-03 11:38 UTC, MayurSMahajan commented on frontend/resources/translations/hin.json
> +      "addAboveCmd": "ऑल्ट + क्लिक ",
don't translate shortcuts. keep them like Alt+Click only

2023-10-03 11:38 UTC, MayurSMahajan commented on frontend/resources/translations/hin.json
> +      "addAboveMacCmd": "विकल्प + क्लिक",
same here as above, don't translate shortcuts

2023-10-03 11:38 UTC, MayurSMahajan commented on frontend/resources/translations/hin.json
> +      "getStartedText": "शुरू करो",
replace with शुरू करें

2023-10-03 11:38 UTC, MayurSMahajan commented on frontend/resources/translations/hin.json
> +      "repeatPasswordEmptyError": "दोबारा पासवर्ड खाली नहीं हो सकता",
replace दोबारा with रिपीट

2023-10-03 11:38 UTC, MayurSMahajan commented on frontend/resources/translations/hin.json
> +      "loginStartWithAnonymous": "एक अनाम सत्र से प्रारंभ करें",
use अज्ञात instead of अनाम

2023-10-03 11:38 UTC, MayurSMahajan commented on frontend/resources/translations/hin.json
> +      "buttonText": "दाखिल करना",
use साइन इन करें instead of दाखिल करना, since the latter is a bit unclear.

2023-10-03 11:38 UTC, MayurSMahajan commented on frontend/resources/translations/hin.json
> +      "repeatPasswordEmptyError": "दोबारा पासवर्ड खाली नहीं हो सकता",
Be consistent and use रिपीट

2023-10-03 11:38 UTC, MayurSMahajan commented on frontend/resources/translations/hin.json
> +      "unmatchedPasswordError": "रिपीट पासवर्ड पासवर्ड के समान नहीं है",
रिपीट पासवर्ड और पासवर्ड एक नहीं है

2023-10-03 11:38 UTC, MayurSMahajan commented on frontend/resources/translations/hin.json
> +      "markdown": "मार्कडौं",
keep markdown and csv in english only

2023-10-03 11:38 UTC, MayurSMahajan commented on frontend/resources/translations/hin.json
> +      "fontSize": "फ़ॉन्ट आकार",
अक्षर का आकर

2023-10-03 11:38 UTC, MayurSMahajan commented on frontend/resources/translations/hin.json
> +      "textAndMarkdown": "टेक्स्ट और मार्कडाउन",
keep in english

2023-10-03 11:38 UTC, MayurSMahajan commented on frontend/resources/translations/hin.json
> +      "csv": "सीएसवी",
keep in english

2023-10-03 11:39 UTC, MayurSMahajan commented on frontend/resources/translations/hin.json
> +      "duplicate": "हटाएं",
and delete should be hataye

2023-10-03 11:41 UTC, MayurSMahajan commented
Also review the suggestions I made for this PR: https://github.com/AppFlowy-IO/AppFlowy/pull/2691

2023-10-04 05:45 UTC, MayurSMahajan requested changes
make these corrections and I will review further. Try to think about the broader context of the app. I suggest use the app a few hours and explore various things you can do. This will help you add better translation. Thanks

2023-10-04 05:45 UTC, MayurSMahajan commented on frontend/resources/translations/hin.json
> +        "showNamingDialogWhenCreatingPage": "पेज बनाते समय नामकरण संवाद दिखाएँ"
replace with पृष्ठ बनाते समय उसका नाम लेने के लिए डायलॉग देखे

2023-10-04 05:45 UTC, MayurSMahajan commented on frontend/resources/translations/hin.json
> +        "shortcutIsAlreadyUsed": "यह शॉर्टकट पहले से ही इसके लिए उपयोग किया जा चुका है: {संघर्ष}",
replace {संघर्ष} with {conflict}

Wherever you see something enclosed within {} (curly braces) that is actually a variable name, don't translate them. They act as a placeholder.

2023-10-04 05:45 UTC, MayurSMahajan commented on frontend/resources/translations/hin.json
> +        "couldNotSaveErrorMsg": "शॉर्टकट सहेजे नहीं जा सके, पुनः प्रयास करें"
use शॉर्टकट सेव नहीं जा सके, पुनः प्रयास करें

2023-10-04 05:45 UTC, MayurSMahajan commented on frontend/resources/translations/hin.json
> +        "placeholder": "अनटाइटल्ड"
as earlier

2023-10-04 05:45 UTC, MayurSMahajan commented on frontend/resources/translations/hin.json
> +        "typeAValue": "एक मान टाइप करें...",
use एक व्याख्या टाइप करें... or वैल्यू

2023-10-04 05:45 UTC, MayurSMahajan commented on frontend/resources/translations/hin.json
> +        "textFieldName": "टेक्स्ट",
लेख

2023-10-04 05:45 UTC, MayurSMahajan commented on frontend/resources/translations/hin.json
> +        "createdAtFieldName": "समय बनाया गया",
बनाने का समय

2023-10-04 05:45 UTC, MayurSMahajan commented on frontend/resources/translations/hin.json
> +        "multiSelectFieldName": "मल्टीसेलेक्ट",
बहु चुनाव

2023-10-04 05:45 UTC, MayurSMahajan commented on frontend/resources/translations/hin.json
> +        "singleSelectFieldName": "चुनें",
चुनाव

2023-10-04 05:45 UTC, MayurSMahajan commented on frontend/resources/translations/hin.json
> +        "numberFieldName": "नंबर",
संख्या

2023-10-04 05:45 UTC, MayurSMahajan commented on frontend/resources/translations/hin.json
> +        "timeFormatTwelveHour": "12 घंटा",
१२

2023-10-04 05:45 UTC, MayurSMahajan commented on frontend/resources/translations/hin.json
> +        "timeFormatTwentyFourHour": "24 घंटे",
२४

2023-10-04 05:45 UTC, MayurSMahajan commented on frontend/resources/translations/hin.json
> +        "clearDate": "तिथि साफ़ करें",
तिथि मिटाए

2023-10-04 05:45 UTC, MayurSMahajan commented on frontend/resources/translations/hin.json
> +        "editProperty": "संपत्ति संपादित करें",
here property does not mean wealth, it means the type of data in the row or column of the database.
Please use डेटा का प्रकार for property from now on
and in this case use डेटा का प्रकार बदले

2023-10-04 05:45 UTC, MayurSMahajan commented on frontend/resources/translations/hin.json
> +        "newProperty": "नई संपत्ति",
same as above

2023-10-04 05:45 UTC, MayurSMahajan commented on frontend/resources/translations/hin.json
> +        "deleteFieldPromptMessage": "क्या आप निश्चित हैं? यह संपत्ति हटा दी जाएगी",
read them after you translate, try to think about the context you are translating them for.

2023-10-04 05:45 UTC, MayurSMahajan commented on frontend/resources/translations/hin.json
> +        "titlePlaceholder": "अनटाइटल्ड",
same as mentioned before

2023-10-04 05:45 UTC, MayurSMahajan commented on frontend/resources/translations/hin.json
> +        "textPlaceholder": "खाली",
रिक्त

2023-10-04 05:45 UTC, MayurSMahajan commented on frontend/resources/translations/hin.json
> +        "count": "गिनो",
गिनती

2023-10-04 18:27 UTC, CrazyRikin commented
@MayurSMahajan please review the changes .

2023-10-05 01:37 UTC, LucasXu0 approved these changes

2023-10-05 04:20 UTC, AmanNegi reviewed
Here are a few suggestions, to improve the translations.

2023-10-05 04:45 UTC, MayurSMahajan commented on frontend/resources/translations/hin.json
> +    "githubStarText": "गिटहब पर स्टार लगाएं",
I agree

2023-10-05 16:02 UTC, CrazyRikin commented
made the changes.

2023-10-10 17:29 UTC, CrazyRikin commented
@MayurSMahajan , @AmanNegi what's the update?

2023-10-11 10:35 UTC, AmanNegi requested changes
Here are some of the changes I would suggest.

2023-10-11 10:35 UTC, AmanNegi commented on frontend/resources/translations/hin.json
> +          "couldNotFetchImage": "चित्र नहीं लाया जा सका",
It would be nice to use the same word for image, either "चित्र" or "छवि".

2023-10-11 10:35 UTC, AmanNegi commented on frontend/resources/translations/hin.json
> +          "left": "बांया ",
Typo, additional spacing.

2023-10-11 10:35 UTC, AmanNegi commented on frontend/resources/translations/hin.json
> +          "cut": "काटो",
`"कट करे"` should be more appropriate.

2023-10-11 18:01 UTC, MayurSMahajan commented on frontend/resources/translations/hin.json
> +      "referencePage": "यह {नाम} रफेरेंसेड है",
absolutely it should be `{name}` since it is a placeholder variable.

2023-10-11 18:01 UTC, MayurSMahajan commented on frontend/resources/translations/hin.json
> +        "path": "दस्तावेज़/प्रवाह"
yes, it is rather confusing, just keep it as is

2023-10-13 16:57 UTC, MayurSMahajan commented
@CrazyRikin whenever you solve any reviews we have raised, you can click the button of resolve conversation to mark those suggestions as complete.

2023-10-15 12:31 UTC, CrazyRikin commented
hey @AmanNegi @MayurSMahajan . pls review the changes.

2023-10-15 14:13 UTC, merged