feat: edit the field by clicking on the drag icon
AppFlowy-IO/AppFlowy pull request #3656
Opened 2023-10-09 16:58 UTC by ekakshjanweja

### Feature Preview

---

#### PR Checklist

- [ ] My code adheres to [AppFlowy's Conventions](https://docs.appflowy.io/docs/documentation/software-contributions/conventions)
- [ ] I've listed at least one issue that this PR fixes in the description above.
- [ ] I've added a test(s) to validate changes in this PR, or this PR only contains semantic changes.
- [ ] All existing tests are passing.

2023-10-09 16:58 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/AppFlowy-IO/AppFlowy?pullRequest=3656) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/AppFlowy-IO/AppFlowy?pullRequest=3656) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/AppFlowy-IO/AppFlowy?pullRequest=3656) it.</sub>

2023-10-10 02:55 UTC, richardshiue commented
Hi there @ekakshjanweja, great progress! I have some feedback:

- There's no need to update the pubspec.lock, and I also think importing dart:io isn't necessary here (and renaming log as well)
- The tooltip text needs to be through i18n

What do you think about the use of blockactionbutton here @LucasXu0 ?

2023-10-11 06:22 UTC, Xazin commented
Seems something went wrong when rebasing/merging main.

Your PR contains changes of earlier commits, and there is still an unresolved conflict.

If you don't mind I can resolve it for you, let me know.

2023-10-11 09:16 UTC, Xazin commented
@ekakshjanweja I've fixed it, but it is now "my" commit, do this to take ownership:

0. Make sure you don't have any changes on your current branch
1. Check out the current state of the branch:
```
git fetch
git reset --hard origin/edit-field-by-drag-icon
```
2. Make sure you don't have any non-committed changes, and then
```
git reset --soft HEAD~1
git commit -m "feat: edit the field by clicking on the drag icon"
git push --force
```

---

The above will alter the commit history, thus needing you to push with force. It's the same I did above.

2023-10-11 14:07 UTC, LucasXu0 commented
@ekakshjanweja Thank you for your contribution. Please sign the CLA and attach a screenshot to demonstrate this feature.

Here are the steps for updating the translation.

1. add your translations to `frontend/resources/translations/en.json`
2. ```cd frontend && sh scripts/code_generation/language_files/generate_language_files.sh```
3. replace the hardcode string with translation key.

2023-10-12 02:42 UTC, richardshiue requested changes
The block action button is supposed to be hidden when not hovering over that row in the property list.

![Screenshot 2023-10-12 at 10 41 22 AM](https://github.com/AppFlowy-IO/AppFlowy/assets/71320345/12d34566-8e39-4a2b-bd40-a9348800d42d)

2023-10-12 03:35 UTC, ekakshjanweja commented
> The block action button is supposed to be hidden when not hovering over that row in the property list.
> 
> ![Screenshot 2023-10-12 at 10 41 22 AM](https://user-images.githubusercontent.com/71320345/274464623-12d34566-8e39-4a2b-bd40-a9348800d42d.png)

Okay I will look into it.

2023-10-12 03:40 UTC, ekakshjanweja commented
@richardshiue I addressed the requested changes.

2023-10-12 06:45 UTC, richardshiue commented on frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/row_property.dart
> +          controller: _popoverController,
Don't use the same _popoverController as below. This makes the popover appear in the wrong place.

2023-10-12 06:45 UTC, richardshiue commented on frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/row_property.dart
> +            width: 160,
We probably don't need a 160px wide sized box here

2023-10-12 06:45 UTC, richardshiue commented on frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/row_property.dart
> +                : null,
You should be checking _isFieldHover before AppFlowyPopover

2023-10-13 02:09 UTC, richardshiue approved these changes
LGTM

2023-10-13 07:17 UTC, ekakshjanweja commented
@richardshiue Shall we merge this then?

2023-10-13 15:47 UTC, merged

2023-10-13 15:48 UTC, richardshiue commented
Merging despite integration test fails. failed test on ubuntu succeeded on windows and vice versa.

2023-10-13 17:30 UTC, ekakshjanweja commented
@richardshiue @Xazin @LucasXu0 Thanks for helping me out throughout the process 🙏. I will be now looking forward to more issues.

2023-10-14 05:07 UTC, richardshiue commented
Thanks for your contribution! Looking forward to your next one!